### ISSUE TITLE
Failed to create mountpoint.

### ISSUE THREAD

**Issue by SK-sep** [Samgisaninja/SuccessionRestore#29]
How to fix 
Failed to create mountpoint. you don't have permission to save the file "mnt1" in the folder "MobileSoftwareUpdate"

**Comment by IMS212** [comment]
Reboot, then delete /var/MobileSoftwareUpdate/mnt1 if it exists.

**Comment by Samgisaninja** [comment]
so this is the issue here; that particular path is the iOS mountpoint:

* to create that path, you must not only be root, but also have kernel-level permissions
* to mount anywhere other than that path, you must have kernel-level permissions
* to get kernel creds, you have to use exploitation, which is not something I'm capable of, and might also cause a kernel panic, which is not something I'm interested in dealing with

So on 95% of devices, this folder exists already and I can use it. But for reasons I don't know, it doesn't exist on some devices, and if it doesn't exist, I can't create it.

¯\_(ツ)_/¯

**Comment by SK-sep** [comment]
oh i see
now this problem is solved

but now im stuck on pop up "mounting filesystem.... this step might fail,if it does, you may need to reboot to get this to work"
whats mean ?

**Comment by Halo-Michael** [comment]
1.snappy -f / -r orig-fs --to real-orig-fs
2.snappy -f / -c snapshot
3.snappy -f / -r snapshot -x
4.reboot, and jailbreak for twice
Now you got /var/MobileSoftwareUpdate/mnt1, system re-created it
to revent your real orig system snapshot:
5.snappy -f / -d orig-fs
6.snappy -f / -r real-orig-fs --to orig-fs

**Comment by SK-sep** [comment]
how to run it ?

**Comment by Halo-Michael** [comment]
> how to run it ?

Via Terminal, and install snappy first.

**Comment by SK-sep** [comment]
> 1.snappy -f / -r orig-fs --to real-orig-fs
> 2.snappy -f / -c snapshot
> 3.snappy -f / -r snapshot -x
> 4.reboot, and jailbreak for twice
> Now you got /var/MobileSoftwareUpdate/mnt1, system re-created it
> to revent your real orig system snapshot:
> 5.snappy -f / -d orig-fs
> 6.snappy -f / -r real-orig-fs --to orig-fs

Done. the mnt1 show up now 
but now the problem is when i want restore, and click "Erase iPhone" on succession app, show popup "mounting filesystem.... this step might fail,if it does, you may need to reboot to get this to work"

[Sreenshoot](https://imgur.com/MgVaDjI)

**Comment by Halo-Michael** [comment]
> > 1.snappy -f / -r orig-fs --to real-orig-fs
> > 2.snappy -f / -c snapshot
> > 3.snappy -f / -r snapshot -x
> > 4.reboot, and jailbreak for twice
> > Now you got /var/MobileSoftwareUpdate/mnt1, system re-created it
> > to revent your real orig system snapshot:
> > 5.snappy -f / -d orig-fs
> > 6.snappy -f / -r real-orig-fs --to orig-fs
> 
> Done. the mnt1 show up now
> but now the problem is when i want restore, and click "Erase iPhone" on succession app, show popup "mounting filesystem.... this step might fail,if it does, you may need to reboot to get this to work"
> 
> [Sreenshoot](https://imgur.com/MgVaDjI)

run those commands and give me the feedback:
1.ls /dev
2.mount
3.snappy -f / -l

**Comment by SK-sep** [comment]
> > > 1.snappy -f / -r orig-fs --to real-orig-fs
> > > 2.snappy -f / -c snapshot
> > > 3.snappy -f / -r snapshot -x
> > > 4.reboot, and jailbreak for twice
> > > Now you got /var/MobileSoftwareUpdate/mnt1, system re-created it
> > > to revent your real orig system snapshot:
> > > 5.snappy -f / -d orig-fs
> > > 6.snappy -f / -r real-orig-fs --to orig-fs
> > 
> > 
> > Done. the mnt1 show up now
> > but now the problem is when i want restore, and click "Erase iPhone" on succession app, show popup "mounting filesystem.... this step might fail,if it does, you may need to reboot to get this to work"
> > [Sreenshoot](https://imgur.com/MgVaDjI)
> 
> run those commands and give me the feedback:
> 1.ls /dev
> 2.mount
> 3.snappy -f / -l

[This](https://imgur.com/AoUPAux)

**Comment by Halo-Michael** [comment]
> > > > 1.snappy -f / -r orig-fs --to real-orig-fs
> > > > 2.snappy -f / -c snapshot
> > > > 3.snappy -f / -r snapshot -x
> > > > 4.reboot, and jailbreak for twice
> > > > Now you got /var/MobileSoftwareUpdate/mnt1, system re-created it
> > > > to revent your real orig system snapshot:
> > > > 5.snappy -f / -d orig-fs
> > > > 6.snappy -f / -r real-orig-fs --to orig-fs
> > > 
> > > 
> > > Done. the mnt1 show up now
> > > but now the problem is when i want restore, and click "Erase iPhone" on succession app, show popup "mounting filesystem.... this step might fail,if it does, you may need to reboot to get this to work"
> > > [Sreenshoot](https://imgur.com/MgVaDjI)
> > 
> > 
> > run those commands and give me the feedback:
> > 1.ls /dev
> > 2.mount
> > 3.snappy -f / -l
> 
> [This](https://imgur.com/AoUPAux)

Try this command:
mount_apfs -o ro /dev/disk3s2s1 /var/MobileSoftwareUpdate/mnt1
or just reboot and re-jailbreak and try again
if after reboot, Succession still can't work, please run "cat /etc/fstab" and give me feedback

**Comment by SK-sep** [comment]
i try reboot and re-jailbreak, succession still problem on mounting system
then i run  "[cat /etc/fstab](https://imgur.com/qBluDYN)"

**Comment by SK-sep** [comment]
> > > > > 1.snappy -f / -r orig-fs --to real-orig-fs
> > > > > 2.snappy -f / -c snapshot
> > > > > 3.snappy -f / -r snapshot -x
> > > > > 4.reboot, and jailbreak for twice
> > > > > Now you got /var/MobileSoftwareUpdate/mnt1, system re-created it
> > > > > to revent your real orig system snapshot:
> > > > > 5.snappy -f / -d orig-fs
> > > > > 6.snappy -f / -r real-orig-fs --to orig-fs
> > > > 
> > > > 
> > > > Done. the mnt1 show up now
> > > > but now the problem is when i want restore, and click "Erase iPhone" on succession app, show popup "mounting filesystem.... this step might fail,if it does, you may need to reboot to get this to work"
> > > > [Sreenshoot](https://imgur.com/MgVaDjI)
> > > 
> > > 
> > > run those commands and give me the feedback:
> > > 1.ls /dev
> > > 2.mount
> > > 3.snappy -f / -l
> > 
> > 
> > [This](https://imgur.com/AoUPAux)
> 
> Try this command:
> mount_apfs -o ro /dev/disk3s2s1 /var/MobileSoftwareUpdate/mnt1
> or just reboot and re-jailbreak and try again
> if after reboot, Succession still can't work, please run "cat /etc/fstab" and give me feedback

i try reboot and re-jailbreak, succession still problem on mounting system
then i run "[cat /etc/fstab](https://imgur.com/qBluDYN)"

**Comment by Samgisaninja** [comment]
@Halo-Michael WOAH! TIL you can do that. I will implement that in the next public release of succession

**Comment by Samgisaninja** [comment]
oh wait, when you use -x, that deletes all other snapshots present on the system... including realorig-fs...

**Comment by Samgisaninja** [comment]
whoops

**Comment by SK-sep** [comment]
SOLVED

before i got this problem , im install Succession from Bigbos repo. 
i try to install from other repo (c1d3r Repo) and I did not get the issue 

the question is "Whats different" from both of them? and btw what official repo for Succession ?

**Comment by Halo-Michael** [comment]
> oh wait, when you use -x, that deletes all other snapshots present on the system... including realorig-fs...

No
use snapshot_revent to revent to a snapshot, will delete any newer snapshot, older snapshot won't.

**Comment by ghost** [comment]
> How to fix
> Failed to create mountpoint. you don't have permission to save the file "mnt1" in the folder "MobileSoftwareUpdate"

I have found a temporary workaround! Using Filza, navigate to Var/Mobile and find "MobileSoftwareUpdate". Click the tiny "i" and for all three groups, select "Read" "Write" and "Execute". That should fix it. Enjoy!!

**Comment by Halo-Michael** [comment]
> > How to fix
> > Failed to create mountpoint. you don't have permission to save the file "mnt1" in the folder "MobileSoftwareUpdate"
> 
> I have found a temporary workaround! Using Filza, navigate to Var/Mobile and find "MobileSoftwareUpdate". Click the tiny "i" and for all three groups, select "Read" "Write" and "Execute". That should fix it. Enjoy!!

The folder we talk about is "/private/var/MobileSoftwareUpdate", not "/private/var/mobile/MobileSoftwareUpdate".
"/private/var/MobileSoftwareUpdate" is managed directly by the kernel, "/private/var/mobile/MobileSoftwareUpdate" is not.
"/private/var/MobileSoftwareUpdate" has some unique kernel credentials, so it can be directly used to mount Partitions, "/private/var/mobile/MobileSoftwareUpdate" can't

**Comment by ghost** [comment]
> > > How to fix
> > > Failed to create mountpoint. you don't have permission to save the file "mnt1" in the folder "MobileSoftwareUpdate"
> > 
> > 
> > I have found a temporary workaround! Using Filza, navigate to Var/Mobile and find "MobileSoftwareUpdate". Click the tiny "i" and for all three groups, select "Read" "Write" and "Execute". That should fix it. Enjoy!!
> 
> The folder we talk about is "/private/var/MobileSoftwareUpdate", not "/private/var/mobile/MobileSoftwareUpdate".
> "/private/var/MobileSoftwareUpdate" is managed directly by the kernel, "/private/var/mobile/MobileSoftwareUpdate" is not.
> "/private/var/MobileSoftwareUpdate" has some unique kernel credentials, so it can be directly used to mount Partitions, "/private/var/mobile/MobileSoftwareUpdate" can't

The method I have described fixed the issue for me. Try it out!

**Comment by Halo-Michael** [comment]
> > > > How to fix
> > > > Failed to create mountpoint. you don't have permission to save the file "mnt1" in the folder "MobileSoftwareUpdate"
> > > 
> > > 
> > > I have found a temporary workaround! Using Filza, navigate to Var/Mobile and find "MobileSoftwareUpdate". Click the tiny "i" and for all three groups, select "Read" "Write" and "Execute". That should fix it. Enjoy!!
> > 
> > 
> > The folder we talk about is "/private/var/MobileSoftwareUpdate", not "/private/var/mobile/MobileSoftwareUpdate".
> > "/private/var/MobileSoftwareUpdate" is managed directly by the kernel, "/private/var/mobile/MobileSoftwareUpdate" is not.
> > "/private/var/MobileSoftwareUpdate" has some unique kernel credentials, so it can be directly used to mount Partitions, "/private/var/mobile/MobileSoftwareUpdate" can't
> 
> The method I have described fixed the issue for me. Try it out!

"/private/var/mobile/MobileSoftwareUpdate" is useless. It's totally different with "/private/var/MobileSoftwareUpdate" which we really need.

**Comment by Halo-Michael** [comment]
> 重新启动，然后删除/ var / MobileSoftwareUpdate / mnt1（如果存在）。



> Reboot, then delete /var/MobileSoftwareUpdate/mnt1 if it exists.

Please delete it, your irresponsible remarks will mislead people.

**Comment by Halo-Michael** [comment]
> Reboot, then delete /var/MobileSoftwareUpdate/mnt1 if it exists.

Please delete it, your irresponsible remarks will mislead people.

**Comment by a3946** [comment]
> > Reboot, then delete /var/MobileSoftwareUpdate/mnt1 if it exists.
> 
> Please delete it, your irresponsible remarks will mislead people.

Hello. I have the same question. How to fix
Failed to create mountpoint. you don't have permission to save the file "mnt1" in the folder "MobileSoftwareUpdate".

**Comment by Halo-Michael** [comment]
> > > Reboot, then delete /var/MobileSoftwareUpdate/mnt1 if it exists.
> > 
> > 
> > Please delete it, your irresponsible remarks will mislead people.
> 
> Hello. I have the same question. How to fix
> Failed to create mountpoint. you don't have permission to save the file "mnt1" in the folder "MobileSoftwareUpdate".

Please check the six-step tutorial above.

**Comment by voltflake** [comment]
Giving writing permissions with filza on /var/MobileSoftwareUpdate/ worked for me)
I had same error as above.

**Comment by ghost** [comment]
Hey Halo-Michael, as you can see, my workaround worked perfectly for daniladyabin.. 

Thank you daniladyabin for confirming that!

**Comment by Halo-Michael** [comment]
![AA9EB493-C505-4DC7-88A9-8EC6AF7FFA57](https://user-images.githubusercontent.com/45062120/58726799-3df29b00-8415-11e9-9cdb-47994eb0e232.jpeg)
> Hey Halo-Michael, as you can see, my workaround worked perfectly for daniladyabin..
> 
> Thank you daniladyabin for confirming that!

Please try this command: "mount_apfs -s orig-fs / <the folder you just created>"
If you can mount something on the folder that you just create, that means you created a right folder
otherwise you created a useless folder.
Thanks for your testing.

Well, that’s the real command. Github just eat it :(

**Comment by bobbykain** [comment]
> Giving writing permissions with filza on /var/MobileSoftwareUpdate/ worked for me)
> I had same error as above.

This solution worked for me as well.

**Comment by Samgisaninja** [comment]
fixed in 1.3.6

**Comment by billgehts** [comment]
hello, can i recreate a clean snapshot? i will restore via succsession. I have the assumption that my snapshot is corrupt. after restore rootfs is it not clean. files from jailbreak before are still available. when i login to my icloud i can´t restore my sms and i became a error. and my banking app detect a jailbreak. I think I have deleted the first snapshot that system have created. my idea is to do a succsession restore and after that a clean spapshot.

sorry for my bad english
